[2021-11-12 11:35:24,089][main_logger][INFO] - Download data
[2021-11-12 11:35:24,302][main_logger][INFO] - Engineer data
[2021-11-12 11:35:28,687][engineer_data_logger][INFO] - Load data into spark
[2021-11-12 11:35:32,748][engineer_data_logger][INFO] - None
[2021-11-12 11:35:32,844][engineer_data_logger][INFO] - None
[2021-11-12 11:35:32,948][engineer_data_logger][INFO] - None
[2021-11-12 11:35:32,948][engineer_data_logger][INFO] - Do some simple transformations
[2021-11-12 11:36:11,254][engineer_data_logger][INFO] - Find close weather stations to ride stations
[2021-11-12 11:36:11,254][merge_stations_logger][INFO] - Load into pandas
[2021-11-12 11:36:22,079][merge_stations_logger][INFO] - Process 330 ride stations and 4462 weather stations
[2021-11-12 11:36:22,087][merge_stations_logger][INFO] - Building KD-Tree
[2021-11-12 11:36:22,092][merge_stations_logger][INFO] - Query points
[2021-11-12 11:36:22,391][engineer_data_logger][INFO] - None
[2021-11-12 11:36:22,391][engineer_data_logger][INFO] - Cross joining with dates
[2021-11-12 11:36:31,360][engineer_data_logger][INFO] - None
[2021-11-12 11:36:31,360][engineer_data_logger][INFO] - Join with weather data
[2021-11-12 11:36:43,921][engineer_data_logger][INFO] - None
[2021-11-12 11:36:43,921][engineer_data_logger][INFO] - Aggregate weather data
[2021-11-12 11:36:59,405][engineer_data_logger][INFO] - None
[2021-11-12 11:38:26,125][engineer_data_logger][INFO] - Join with ride data
[2021-11-12 11:38:41,737][engineer_data_logger][INFO] - None
[2021-11-12 11:38:41,737][engineer_data_logger][INFO] - Get per day data
[2021-11-12 11:38:50,150][py4j.clientserver][INFO] - Error while receiving.
Traceback (most recent call last):
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\clientserver.py", line 475, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
RuntimeError: reentrant call inside <_io.BufferedReader name=3208>
[2021-11-12 11:38:50,151][py4j.clientserver][INFO] - Closing down clientserver connection
[2021-11-12 11:38:50,152][root][ERROR] - Exception while sending command.
Traceback (most recent call last):
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\clientserver.py", line 475, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
RuntimeError: reentrant call inside <_io.BufferedReader name=3208>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\clientserver.py", line 503, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2021-11-12 11:38:50,153][py4j.clientserver][INFO] - Error while receiving.
Traceback (most recent call last):
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\clientserver.py", line 475, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "C:\Users\SuperTom\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\pyspark\context.py", line 292, in signal_handler
    self.cancelAllJobs()
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\pyspark\context.py", line 1195, in cancelAllJobs
    self._jsc.sc().cancelAllJobs()
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\java_gateway.py", line 1309, in __call__
    return_value = get_return_value(
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\pyspark\sql\utils.py", line 111, in deco
    return f(*a, **kw)
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o13.sc
[2021-11-12 11:38:50,156][py4j.clientserver][INFO] - Closing down clientserver connection
[2021-11-12 11:38:50,156][root][ERROR] - Exception while sending command.
Traceback (most recent call last):
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\clientserver.py", line 475, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "C:\Users\SuperTom\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\pyspark\context.py", line 292, in signal_handler
    self.cancelAllJobs()
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\pyspark\context.py", line 1195, in cancelAllJobs
    self._jsc.sc().cancelAllJobs()
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\java_gateway.py", line 1309, in __call__
    return_value = get_return_value(
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\pyspark\sql\utils.py", line 111, in deco
    return f(*a, **kw)
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o13.sc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "C:\Users\SuperTom\PycharmProjects\weather-bike-analysis\venv\lib\site-packages\py4j\clientserver.py", line 503, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
